[workspace]
members = [
    "crates/git-fixture",
]

[package]
name = "git-stack"
description = "Stacked branch management for Git"
version = "0.4.4"
license = "MIT OR Apache-2.0"
repository = "https://github.com/epage/git-stack.git"
documentation = "https://github.com/epage/git-stack.git"
readme = "README.md"
categories = ["command-line-interface", "development-tools"]
keywords = ["git", "cli"]
edition = "2018"
exclude = [
    ".gitignore",
    "CHANGELOG.md",
    "CONTRIBUTING.md",
    "release.toml",
    "typos.toml",
    "committed.toml",
    "docs/**",
    ".github/**",
    "tests/**",
    "benches/**",
]

[package.metadata.release]
pre-release-replacements = [
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}", min=1},
  {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}", exactly=1},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}", min=1},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n## [Unreleased] - ReleaseDate\n", exactly=1},
  {file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n[Unreleased]: https://github.com/epage/git-stack/compare/{{tag_name}}...HEAD", exactly=1},
]

[dependencies]
git2 = { version = "0.13", default-features = false, features = ["vendored-libgit2"] }
git-config-env = "0.1"
log = "0.4"
structopt = "0.3"
clap = "2"
clap-verbosity-flag = "0.3"
proc-exit = "1"
eyre = "0.6"
human-panic = "1"
yansi = "0.5.0"
concolor-control = { version = "0.0.7" }
concolor-clap = { version = "0.0.6", features = ["api_unstable"] }
termtree = "0.2"
env_logger = { version = "0.9", default-features = false, features = ["termcolor"] }
atty = "0.2"
humantime = "2"
itertools = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ignore = "0.4"
bstr = "0.2"
maplit = "1"

[dev-dependencies]
git-fixture = { version = "0.1", path = "crates/git-fixture" }
assert_fs = "1"
