[workspace]
members = [
    "crates/git-fixture",
]

[package]
name = "git-stack"
version = "0.1.0"
edition = "2018"

[dependencies]
git2 = "0.13"
log = "0.4"
structopt = "0.3"
clap = "2"
clap-verbosity-flag = "0.3"
proc-exit = "1"
eyre = "0.6"
human-panic = "1"
yansi = "0.5.0"
treeline = "0.1"
env_logger = { version = "0.8", default-features = false, features = ["termcolor"] }
atty = "0.2"
itertools = "0.10"
serde = { version = "1", features = ["derive"] }
toml = "0.5"
ignore = "0.4"
bstr = "0.2"
