name: Bug report
labels: 'bug'
body:
  - type: checkboxes
    attributes:
      options:
        - label: I have searched the [discussions](https://github.com/epage/git-stack/discussions)
        - label: I have searched the existing issues
