name: "Feature request"
description: "Suggest an idea for this project"
labels: ['question']
body:
  - type: "textarea"
    attributes:
      label: "Possible Solutions"
      description: "A clear and concise description of any solutions or features you've managed to come up with."
